server:
  port: '8081'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermgmt?createDatabaseIfNotExist=true
    username: root
    password: system
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

